### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by GiulioBen** [junyuchen245/COVID19_CT_Segmentation_3DSlicer#1] opened 2020-05-11 12:18 UTC
Dear all, could you please provide a couple of information on how to install the extension?

I tried to clone the github repository into the extension folder of Slicer but it's not working. The manual *zip installation of the extension through extension manager is not working too.

Thank you.

Best

Giulio

**Comment by junyuchen245** [comment] 2020-05-11 16:01
Hi,

First of all, all the required packages must be installed under Slicer (e.g. TensorFlow, scikit-image, etc.). If you are using mac, this is how you can do it:
1. cd ~/Applications/Slicer.app/Contents/bin
2. ./PythonSlicer -m pip install scikit-image


To install my module:
1. go to Extension Wizard
2. Choose ''Select Extension", then select the directory that contains this module (I suggest you make a new directory for it).

I hope this helps.

Junyu

> Dear all, could you please provide a couple of information on how to install the extension?
> 
> I tried to clone the github repository into the extension folder of Slicer but it's not working. The manual *zip installation of the extension through extension manager is not working too.
> 
> Thank you.
> 
> Best
> 
> Giulio

**Comment by GiulioBen** [comment] 2020-05-11 18:26
Thank you for your support. I really appreciate it.

I was missing the extension wizard module!

I run 
`/Applications/Slicer.app/Contents/bin/PythonSlicer -m pip install Keras Tensorflow scikit-image scipy numpy`

and from the extension wizard module I imported the folder _COVID19_CT_SEGMENTATION_ .

However I get the following error.

```
Using TensorFlow backend.
/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/Giulio/Downloads/COVID19_CT_Segmentation_3DSlicer-master/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py", line 12, in <module>
    from skimage.exposure import rescale_intensity
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/skimage/__init__.py", line 133, in <module>
    from .data import data_dir
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/skimage/data/__init__.py", line 60, in <module>
    import pooch
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pooch/__init__.py", line 7, in <module>
    from .processors import Unzip, Untar, Decompress
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pooch/processors.py", line 8, in <module>
    import lzma
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```
I use a nightly version of 3D slicer.

I tried to remake it under ubuntu but the same error appears.
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gb/COVID19_CT_Segmentation_3DSlicer/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py", line 12, in <module>
    from skimage.exposure import rescale_intensity
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/__init__.py", line 133, in <module>
    from .data import data_dir
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/data/__init__.py", line 60, in <module>
    import pooch
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/__init__.py", line 7, in <module>
    from .processors import Unzip, Untar, Decompress
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/processors.py", line 8, in <module>
    import lzma
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gb/COVID19_CT_Segmentation_3DSlicer/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py", line 12, in <module>
    from skimage.exposure import rescale_intensity
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/__init__.py", line 133, in <module>
    from .data import data_dir
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/data/__init__.py", line 60, in <module>
    import pooch
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/__init__.py", line 7, in <module>
    from .processors import Unzip, Untar, Decompress
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/processors.py", line 8, in <module>
    import lzma
  File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
The module factory manager reported an error. One or more of the requested module(s) and/or dependencies thereof may not have been loaded.

```


If you need more tests I'm available. Best regards.

**Comment by junyuchen245** [comment] 2020-05-11 19:58
> Thank you for your support. I really appreciate it.
> 
> I was missing the extension wizard module!
> 
> I run
> `/Applications/Slicer.app/Contents/bin/PythonSlicer -m pip install Keras Tensorflow scikit-image scipy numpy`
> 
> and from the extension wizard module I imported the folder _COVID19_CT_SEGMENTATION_ .
> 
> However I get the following error.
> 
> ```
> Using TensorFlow backend.
> /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
>   warnings.warn(msg)
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/imp.py", line 170, in load_source
>     module = _exec(spec, sys.modules[name])
>   File "<frozen importlib._bootstrap>", line 618, in _exec
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/Users/Giulio/Downloads/COVID19_CT_Segmentation_3DSlicer-master/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py", line 12, in <module>
>     from skimage.exposure import rescale_intensity
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/skimage/__init__.py", line 133, in <module>
>     from .data import data_dir
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/skimage/data/__init__.py", line 60, in <module>
>     import pooch
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pooch/__init__.py", line 7, in <module>
>     from .processors import Unzip, Untar, Decompress
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pooch/processors.py", line 8, in <module>
>     import lzma
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/lzma.py", line 27, in <module>
>     from _lzma import *
> ModuleNotFoundError: No module named '_lzma'
> ```
> 
> I use a nightly version of 3D slicer.
> 
> I tried to remake it under ubuntu but the same error appears.
> 
> ```
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
>     module = _exec(spec, sys.modules[name])
>   File "<frozen importlib._bootstrap>", line 618, in _exec
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/gb/COVID19_CT_Segmentation_3DSlicer/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py", line 12, in <module>
>     from skimage.exposure import rescale_intensity
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/__init__.py", line 133, in <module>
>     from .data import data_dir
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/data/__init__.py", line 60, in <module>
>     import pooch
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/__init__.py", line 7, in <module>
>     from .processors import Unzip, Untar, Decompress
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/processors.py", line 8, in <module>
>     import lzma
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/lzma.py", line 27, in <module>
>     from _lzma import *
> ModuleNotFoundError: No module named '_lzma'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
>     module = _exec(spec, sys.modules[name])
>   File "<frozen importlib._bootstrap>", line 618, in _exec
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/gb/COVID19_CT_Segmentation_3DSlicer/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py", line 12, in <module>
>     from skimage.exposure import rescale_intensity
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/__init__.py", line 133, in <module>
>     from .data import data_dir
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/data/__init__.py", line 60, in <module>
>     import pooch
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/__init__.py", line 7, in <module>
>     from .processors import Unzip, Untar, Decompress
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/processors.py", line 8, in <module>
>     import lzma
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/lzma.py", line 27, in <module>
>     from _lzma import *
> ModuleNotFoundError: No module named '_lzma'
> The module factory manager reported an error. One or more of the requested module(s) and/or dependencies thereof may not have been loaded.
> ```
> 
> If you need more tests I'm available. Best regards.

I'm using an older version of Slicer on mac, so maybe they changed something now. I will do some tests on my Windows machine, will let you know soon.

Thanks,
Junyu

**Comment by junyuchen245** [comment] 2020-05-11 21:41
> Thank you for your support. I really appreciate it.
> 
> I was missing the extension wizard module!
> 
> I run
> `/Applications/Slicer.app/Contents/bin/PythonSlicer -m pip install Keras Tensorflow scikit-image scipy numpy`
> 
> and from the extension wizard module I imported the folder _COVID19_CT_SEGMENTATION_ .
> 
> However I get the following error.
> 
> ```
> Using TensorFlow backend.
> /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
>   warnings.warn(msg)
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/imp.py", line 170, in load_source
>     module = _exec(spec, sys.modules[name])
>   File "<frozen importlib._bootstrap>", line 618, in _exec
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/Users/Giulio/Downloads/COVID19_CT_Segmentation_3DSlicer-master/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py", line 12, in <module>
>     from skimage.exposure import rescale_intensity
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/skimage/__init__.py", line 133, in <module>
>     from .data import data_dir
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/skimage/data/__init__.py", line 60, in <module>
>     import pooch
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pooch/__init__.py", line 7, in <module>
>     from .processors import Unzip, Untar, Decompress
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pooch/processors.py", line 8, in <module>
>     import lzma
>   File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/lzma.py", line 27, in <module>
>     from _lzma import *
> ModuleNotFoundError: No module named '_lzma'
> ```
> 
> I use a nightly version of 3D slicer.
> 
> I tried to remake it under ubuntu but the same error appears.
> 
> ```
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
>     module = _exec(spec, sys.modules[name])
>   File "<frozen importlib._bootstrap>", line 618, in _exec
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/gb/COVID19_CT_Segmentation_3DSlicer/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py", line 12, in <module>
>     from skimage.exposure import rescale_intensity
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/__init__.py", line 133, in <module>
>     from .data import data_dir
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/data/__init__.py", line 60, in <module>
>     import pooch
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/__init__.py", line 7, in <module>
>     from .processors import Unzip, Untar, Decompress
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/processors.py", line 8, in <module>
>     import lzma
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/lzma.py", line 27, in <module>
>     from _lzma import *
> ModuleNotFoundError: No module named '_lzma'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
>     module = _exec(spec, sys.modules[name])
>   File "<frozen importlib._bootstrap>", line 618, in _exec
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/gb/COVID19_CT_Segmentation_3DSlicer/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py", line 12, in <module>
>     from skimage.exposure import rescale_intensity
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/__init__.py", line 133, in <module>
>     from .data import data_dir
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/skimage/data/__init__.py", line 60, in <module>
>     import pooch
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/__init__.py", line 7, in <module>
>     from .processors import Unzip, Untar, Decompress
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/site-packages/pooch/processors.py", line 8, in <module>
>     import lzma
>   File "/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/lib/Python/lib/python3.6/lzma.py", line 27, in <module>
>     from _lzma import *
> ModuleNotFoundError: No module named '_lzma'
> The module factory manager reported an error. One or more of the requested module(s) and/or dependencies thereof may not have been loaded.
> ```
> 
> If you need more tests I'm available. Best regards.

Looks like the errors were caused by Slicer: https://github.com/Slicer/Slicer/issues/4920. So, scikit-image won't work because it depends on the "lzma" package. Fortunately, it still supports Keras, TF, scipy, and cv2. I uploaded a new version that does not depend on scikit-image, you can find the files here: https://github.com/junyuchen245/COVID19_CT_Segmentation_3DSlicer/tree/master/Slicer_4.11_tested.


Be sure to:
1. install all the required package: `Keras`, `Tensorflow`, `opencv-python`, `scipy`, and `numpy`. You can do it with `PythonSlicer -m pip install xxx`

2. change the location of the CNN model before you import the extension module into Slicer. In Slicer_4.11_tested/COVID19_CT_SEGMENTATION/ConvNetCovid/ConvNetCovid.py:
    `Line 52: segmentation_model = load_model('xxx_Model.h5')`

I hope this solves your problem.
Junyu

**Comment by junyuchen245** [comment] 2020-05-11 21:44
I have also uploaded a test image: https://github.com/junyuchen245/COVID19_CT_Segmentation_3DSlicer/blob/master/data2.nrrd.
You can simply drag and drop this file into Slicer.

Junyu

**Comment by GiulioBen** [comment] 2020-05-12 07:09
Thank you for your prompt response.

Now I have the following error.



```
Failed to open extension '/Users/Giulio/Downloads/COVID19_CT_Segmentation_3DSlicer-master/Slicer_4.11_tested/COVID19_CT_SEGMENTATION/ConvNetCovid'.
Using TensorFlow backend.
/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
/Applications
/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
```


I used the *tested* version and verified all the installations on PythonSlicer (not SlicerPython?).
Thanks

**Comment by junyuchen245** [comment] 2020-05-12 08:00
> Thank you for your prompt response.
> 
> 
> 
> Now I have the following error.
> 
> 
> 
> 
> 
> 
> 
> ```
> 
> Failed to open extension '/Users/Giulio/Downloads/COVID19_CT_Segmentation_3DSlicer-master/Slicer_4.11_tested/COVID19_CT_SEGMENTATION/ConvNetCovid'.
> 
> Using TensorFlow backend.
> 
> /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
> 
>   warnings.warn(msg)
> 
> /Applications
> 
> /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
> 
>   warnings.warn('No training configuration found in save file: '
> 
> ```
> 
> 
> 
> 
> 
> I used the *tested* version and verified all the installations on PythonSlicer (not SlicerPython?).
> 
> Thanks

Hmm... That’s weird, I tested it this afternoon on a Windows PC using Slicer 4.11, it was fine. It seems like the error was still caused by the missing of the lzma package. Unfortunately, there is nothing else I can do.
Here are my suggestions:
1. You can watch this thread (https://github.com/Slicer/Slicer/issues/4920) closely and wait until they fix this bug. I would imagine that it will be fixed soon, as many other Slicer extension modules also deeply rely on ‘lzma’ package.

2. If you really want to try this module immediately, then I suggest you to install an older version of Slicer. From our previous discussions, I see that you are using Mac/Linux. Our module was firstly implemented and tested using Slicer 3.8 on a MacBook, and it seems to work just fine. Here is the link to the older versions of Slicer: http://slicer.kitware.com/midas3/folder/274

Btw, here is a tutorial about installing python packages in Slicer: https://www.slicer.org/wiki/Documentation/Nightly/Developers/FAQ/Python_Scripting
According to this, we should use PythonSlicer instead of SlicerPython to install packages. I’m not so sure what SlicerPython is for.

I’m sorry that I couldn’t be more helpful.

Junyu

**Comment by GiulioBen** [comment] 2020-05-12 08:12
Thank you for your support, I'll try using an old version of Slicer.

Best

**Comment by GiulioBen** [comment] 2020-05-12 11:34
FYI, under ubuntu, everything installed through pip + 
the correct path for the model in the py script (the 4.11_tested version)
it makes Slicer crash. Opening Slicer from shell

```
Switch to module:  "Welcome"
Switch to module:  "ExtensionWizard"
Using TensorFlow backend.
error: [/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
```
I'll try with an older Slicer Version.

**Comment by junyuchen245** [comment] 2020-05-12 14:46
> FYI, under ubuntu, everything installed through pip +
> the correct path for the model in the py script (the 4.11_tested version)
> it makes Slicer crash. Opening Slicer from shell
> 
> ```
> Switch to module:  "Welcome"
> Switch to module:  "ExtensionWizard"
> Using TensorFlow backend.
> error: [/home/gb/Slicer-4.11.0-2019-12-09-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
> ```
> 
> I'll try with an older Slicer Version.

Thanks for letting me know. I hope an older version works better.

Junyu

**Closed as completed** 2020-05-13 18:28 UTC

**Comment by LuisOtavioSantos** [comment] 2022-02-20 19:26
I managed to install it.

After installing all packages mentioned I had to change the multi_process_lib.py file:
put the following at the script header:

import sys

if not hasattr(sys, 'argv'):
    sys.argv  = [''] 

Then change the project file ConvNetCovid.py: 

from this:
'from keras.utils import to_categorical'
to this:
'from tensorflow.keras.utils import to_categorical'

after restarting, it works.
